name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Make Release on PyPI and Github
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Build Tools
        run: pip install build

      - name: Build a binary wheel
        run: |
          python -m build -s .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.2
